services:
  database:
    container_name: database_postgres
    image: postgres:17.7-bookworm
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - mt_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mt_net

volumes:
  mt_pgdata:

networks:
  mt_net: